package views;

import java.awt.Dimension;

import javax.swing.JPanel;

import model.CalcController;
import java.awt.Color;
import javax.swing.border.LineBorder;

/**
 * Definition of a numpad view.
 * 
 * @author MasonS
 * @version 1.0
 */
public abstract class Numpad extends JPanel
{
    private CalcController controller;
    
    /**
     * Constructor for the Numpad class.
     * 
     * @param newController A controller for the parent gui.
     */
    public Numpad(CalcController newController)
    {
        //AUTO GENERATED BY WINDOWBUILDER PRO FOR ECLIPSE
        setBorder(new LineBorder(new Color(0, 0, 0), 2, true));
        setBackground(new Color(105, 105, 105));
        controller = newController;
        setName("Numpad");
        setPreferredSize(new Dimension(496, 295));
    }
    
    /**
     * Returns the controller.
     * @return Returns the controller.
     */
    public CalcController getController()
    {
        return controller;
    }
}
