package plugins;

import java.awt.Dimension;
import java.awt.Font;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.awt.Insets;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JMenuItem;

import views.ControlPanel;
import views.Numpad;
import views.DefaultControlPanel;
import model.CalcController;
import model.Calculator;
import model.CalculatorPlugin;

/**
 * Replaces the standard numpad with a numpad containing roman numerals.
 * Replaces the standard calculator with one that evaluates all operations to
 * "XVII".
 * 
 * Note that if the JMenuItem abt was not static and we did not check its
 * value, it would get added to the help menu every single time the user 
 * selects this plugin.
 * 
 * @author MasonS
 * @version 1.0
 */
public class RomanPlugin extends CalculatorPlugin
{
    private static JMenuItem abt = null;
    private static String pluginInfo = 
            "The RomanPlugin is a simple plugin for the calculator framework"
            + " that replaces the default numpad with a numpad containing"
            + " roman numerals.\n Additionally, it overrides the default"
            + " calculator logic, causing every operation to evaluate to"
            + "\"XVII\"\n";
    
    /**
     * Constructor for RomanPlugin.
     * @param newController A controller for this plugin's parent gui.
     */
    public RomanPlugin(CalcController newController)
    {
        super(newController);
        
        //check to see if help menu item has already been added
        if (abt == null)
        {
            abt = new JMenuItem("About RomanPlugin");
            abt.addActionListener(new ActionListener() {

                @Override
                public void actionPerformed(ActionEvent e)
                {
                    getController().notify(pluginInfo);
                }
                
            });
            getController().addToHelp(abt, 0);
            //System.out.println("About roman added");
        }
    }
    
    /**
     * {@inheritDoc}
     */
    @Override
    public Numpad getNumpad()
    {
        return new RomanNumpad(getController());
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ControlPanel getControlPanel()
    {
        return null;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Calculator getCalculator()
    {
        return new RomanCalculator();
    }

    /**
     * Custom calculator for RomanPlugin.
     */
    private class RomanCalculator implements Calculator
    {

        @Override
        public String processCommand(String command)
        {
            // check for valid command
            if (command.length() == 0)
            {
                return kInvalidOperation;
            }

            // evaluates all operations the same
            else
            {
                return "Result: XVII";
            }
        }

    }

    /**
     * Custom numpad for RomanPlugin.
     */
    private class RomanNumpad extends Numpad
    {
        public RomanNumpad(CalcController newController)
        {
            //AUTO GENERATED BY WINDOWBUILDER PRO FOR ECLIPSE
            super(newController);

            GridBagLayout gridBagLayout = new GridBagLayout();
            gridBagLayout.columnWidths = new int[] { 60, 60, 50 };
            gridBagLayout.rowHeights = new int[] { 50, 50, 50, 50 };
            gridBagLayout.columnWeights = new double[] { 0.0 };
            gridBagLayout.rowWeights = new double[] { 0.0 };
            setLayout(gridBagLayout);

            initButtonRowOne();
            initButtonRowTwo();
            initButtonRowThree();
            initButtonRowFour();
        }
        
        private void initButtonRowOne()
        {
            //AUTO GENERATED BY WINDOWBUILDER PRO FOR ECLIPSE
            JButton seven = new JButton("VII");
            seven.addActionListener(new ActionListener()
            {
                public void actionPerformed(ActionEvent arg0)
                {
                    getController().append("7");
                }
            });
            seven.setMinimumSize(new Dimension(60, 50));
            seven.setMaximumSize(new Dimension(60, 50));
            seven.setFont(new Font("Times New Roman", Font.PLAIN, 12));
            seven.setPreferredSize(new Dimension(60, 50));
            GridBagConstraints gbcSeven = new GridBagConstraints();
            gbcSeven.insets = new Insets(0, 0, 5, 20);
            gbcSeven.gridx = 0;
            gbcSeven.gridy = 0;
            add(seven, gbcSeven);

            JButton eight = new JButton("VIII");
            eight.addActionListener(new ActionListener()
            {
                public void actionPerformed(ActionEvent arg0)
                {
                    getController().append("8");
                }
            });
            eight.setPreferredSize(new Dimension(60, 50));
            eight.setFont(new Font("Times New Roman", Font.PLAIN, 12));
            GridBagConstraints gbcEight = new GridBagConstraints();
            gbcEight.insets = new Insets(0, 0, 5, 20);
            gbcEight.gridx = 1;
            gbcEight.gridy = 0;
            add(eight, gbcEight);

            JButton btnIx = new JButton("IX");
            btnIx.addActionListener(new ActionListener()
            {
                public void actionPerformed(ActionEvent arg0)
                {
                    getController().append("9");
                }
            });
            btnIx.setFont(new Font("Times New Roman", Font.PLAIN, 12));
            btnIx.setPreferredSize(new Dimension(60, 50));
            GridBagConstraints gbcBtnIx = new GridBagConstraints();
            gbcBtnIx.insets = new Insets(0, 0, 5, 0);
            gbcBtnIx.gridx = 2;
            gbcBtnIx.gridy = 0;
            add(btnIx, gbcBtnIx);
        }
        
        private void initButtonRowTwo()
        {
            //AUTO GENERATED BY WINDOWBUILDER PRO FOR ECLIPSE
            JButton btnIv = new JButton("IV");
            btnIv.addActionListener(new ActionListener()
            {
                public void actionPerformed(ActionEvent arg0)
                {
                    getController().append("4");
                }
            });
            btnIv.setFont(new Font("Times New Roman", Font.PLAIN, 12));
            btnIv.setPreferredSize(new Dimension(60, 50));
            GridBagConstraints gbcBtnIv = new GridBagConstraints();
            gbcBtnIv.insets = new Insets(0, 0, 5, 20);
            gbcBtnIv.gridx = 0;
            gbcBtnIv.gridy = 1;
            add(btnIv, gbcBtnIv);

            JButton btnV = new JButton("V");
            btnV.addActionListener(new ActionListener()
            {
                public void actionPerformed(ActionEvent arg0)
                {
                    getController().append("5");
                }
            });
            btnV.setFont(new Font("Times New Roman", Font.PLAIN, 12));
            btnV.setPreferredSize(new Dimension(60, 50));
            GridBagConstraints gbcBtnV = new GridBagConstraints();
            gbcBtnV.insets = new Insets(0, 0, 5, 20);
            gbcBtnV.gridx = 1;
            gbcBtnV.gridy = 1;
            add(btnV, gbcBtnV);

            JButton btnVi = new JButton("VI");
            btnVi.addActionListener(new ActionListener()
            {
                public void actionPerformed(ActionEvent arg0)
                {
                    getController().append("6");
                }
            });
            btnVi.setFont(new Font("Times New Roman", Font.PLAIN, 12));
            btnVi.setPreferredSize(new Dimension(60, 50));
            GridBagConstraints gbcBtnVi = new GridBagConstraints();
            gbcBtnVi.insets = new Insets(0, 0, 5, 0);
            gbcBtnVi.gridx = 2;
            gbcBtnVi.gridy = 1;
            add(btnVi, gbcBtnVi);
        }
        
        private void initButtonRowThree()
        {
            //AUTO GENERATED BY WINDOWBUILDER PRO FOR ECLIPSE
            JButton btnI = new JButton("I");
            btnI.addActionListener(new ActionListener()
            {
                public void actionPerformed(ActionEvent arg0)
                {
                    getController().append("1");
                }
            });
            btnI.setFont(new Font("Times New Roman", Font.PLAIN, 12));
            btnI.setPreferredSize(new Dimension(60, 50));
            GridBagConstraints gbcBtnI = new GridBagConstraints();
            gbcBtnI.insets = new Insets(0, 0, 5, 20);
            gbcBtnI.gridx = 0;
            gbcBtnI.gridy = 2;
            add(btnI, gbcBtnI);

            JButton btnIi = new JButton("II");
            btnIi.addActionListener(new ActionListener()
            {
                public void actionPerformed(ActionEvent arg0)
                {
                    getController().append("2");
                }
            });
            btnIi.setFont(new Font("Times New Roman", Font.PLAIN, 12));
            btnIi.setPreferredSize(new Dimension(60, 50));
            GridBagConstraints gbcBtnIi = new GridBagConstraints();
            gbcBtnIi.insets = new Insets(0, 0, 5, 20);
            gbcBtnIi.gridx = 1;
            gbcBtnIi.gridy = 2;
            add(btnIi, gbcBtnIi);

            JButton btnIii = new JButton("III");
            btnIii.addActionListener(new ActionListener()
            {
                public void actionPerformed(ActionEvent arg0)
                {
                    getController().append("3");
                }
            });
            btnIii.setFont(new Font("Times New Roman", Font.PLAIN, 12));
            btnIii.setPreferredSize(new Dimension(60, 50));
            GridBagConstraints gbcBtnIii = new GridBagConstraints();
            gbcBtnIii.insets = new Insets(0, 0, 5, 0);
            gbcBtnIii.gridx = 2;
            gbcBtnIii.gridy = 2;
            add(btnIii, gbcBtnIii);
        }
        
        private void initButtonRowFour()
        {
            //AUTO GENERATED BY WINDOWBUILDER PRO FOR ECLIPSE
            JButton btnNulla = new JButton("nulla");
            btnNulla.addActionListener(new ActionListener()
            {
                public void actionPerformed(ActionEvent arg0)
                {
                    getController().append("0");
                }
            });
            btnNulla.setFont(new Font("Times New Roman", Font.ITALIC, 12));
            btnNulla.setPreferredSize(new Dimension(60, 50));
            GridBagConstraints gbcBtnNulla = new GridBagConstraints();
            gbcBtnNulla.insets = new Insets(0, 0, 0, 20);
            gbcBtnNulla.gridx = 0;
            gbcBtnNulla.gridy = 3;
            add(btnNulla, gbcBtnNulla);

            JButton button9 = new JButton(".");
            button9.addActionListener(new ActionListener()
            {
                public void actionPerformed(ActionEvent arg0)
                {
                    getController().append(".");
                }
            });
            button9.setFont(new Font("Times New Roman", Font.PLAIN, 12));
            button9.setPreferredSize(new Dimension(60, 50));
            GridBagConstraints gbcBtn9 = new GridBagConstraints();
            gbcBtn9.insets = new Insets(0, 0, 0, 20);
            gbcBtn9.gridx = 1;
            gbcBtn9.gridy = 3;
            add(button9, gbcBtn9);
        }

    }

    /**
     * {@inheritdoc}
     */
    @Override
    public void unload()
    {
        // does nothing...
    }
}
